services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://docker:docker@localhost:5432/egab
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .frontmatter/
            - .vscode/
            - ./.gitignore
        - action: rebuild
          path: package.json
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: egab
    volumes:
      - egab_pg_data:/var/lib/postgresql/data
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
volumes:
  egab_pg_data: