import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import "@govbr-ds/core/dist/core.min.css";
import Head from 'next/head';
import Footer from '@/app/_ui/components/footer/Footer';
import Header from '@/app/_ui/components/header/Header';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: " | Meu Gabinete",
    default: "Meu Gabinete"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdn.dsgovserprodesign.estaleiro.serpro.gov.br/design-system/fonts/rawline/css/rawline.css"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900&amp;display=swap"
        />
      </Head>
      <body className={inter.className}>
        <Header />
    <main className="flex min-h-screen gap-8 flex-col items-center p-24">
        {children}
        </main>
        <Footer />
        </body>
    </html>
  )
}
