import {
  User,
} from "@prisma/client";

const users: User[] = [
  {
    id: "1",
    name: "User 1",
    username: "user1",
    gh_username: "user1_github",
    email: "user1@example.com",
    emailVerified: new Date(),
    image: "user1-image",
    cloudinaryDir: "user1-cloudinary-dir",
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    stripeCustomerId: "user1-stripe-customer-id",
    clientId: "1",
    password: "user1-password",
    role: "Politician",
    websiteId: "",
  },
  {
    id: "1",
    name: "User 1",
    username: "user1",
    gh_username: "user1_github",
    email: "user1@example.com",
    emailVerified: new Date(),
    image: "user1-image",
    cloudinaryDir: "user1-cloudinary-dir",
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    stripeCustomerId: "user1-stripe-customer-id",
    clientId: "1",
    password: "user1-password",
    role: "Politician",
    websiteId: "",
  },
  {
    id: "1",
    name: "User 1",
    username: "user1",
    gh_username: "user1_github",
    email: "user1@example.com",
    emailVerified: new Date(),
    image: "user1-image",
    cloudinaryDir: "user1-cloudinary-dir",
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    stripeCustomerId: "user1-stripe-customer-id",
    clientId: "1",
    password: "user1-password",
    role: "Politician",
    websiteId: "",
  },
  {
    id: "1",
    name: "User 1",
    username: "user1",
    gh_username: "user1_github",
    email: "user1@example.com",
    emailVerified: new Date(),
    image: "user1-image",
    cloudinaryDir: "user1-cloudinary-dir",
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
    stripeCustomerId: "user1-stripe-customer-id",
    clientId: "1",
    password: "user1-password",
    role: "Politician",
    websiteId: "",
  },
];

export default users;
