import { Website } from "@prisma/client";

const websites: Website[] = [
  {
    id: "1",
    cloudinaryDir: "your-cloudinary-dir-1",
    contactId: "1",
    customDomain: "custom-domain-1",
    description: "Website description 1",
    myHistory: "Website history 1",
    name: "Website 1",
    politicianPhoto: "",
    theme: "blue",
    subdomain: "subdomain-1",
    message404: "Parabéns! Você encontrou uma página que não existe.",
    logo: "your-logo-1",
    font: "font-cal",
    imageBlurhash: "your-image-blurhash-1",
    image: "your-image-1",
    politicianId: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    cloudinaryDir: "your-cloudinary-dir-2",
    contactId: "2",
    customDomain: "custom-domain-2",
    description: "Website description 2",
    myHistory: "Website history 2",
    name: "Website 2",
    politicianPhoto: "",
    theme: "blue",
    subdomain: "subdomain-2",
    message404: "Parabéns! Você encontrou uma página que não existe.",
    logo: "your-logo-2",
    font: "font-cal",
    imageBlurhash: "your-image-blurhash-2",
    image: "your-image-2",
    politicianId: "2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    cloudinaryDir: "your-cloudinary-dir-3",
    contactId: "3",
    customDomain: "custom-domain-3",
    description: "Website description 3",
    myHistory: "Website history 3",
    name: "Website 3",
    politicianPhoto: "",
    theme: "blue",
    subdomain: "subdomain-3",
    message404: "Parabéns! Você encontrou uma página que não existe.",
    logo: "your-logo-3",
    font: "font-cal",
    imageBlurhash: "your-image-blurhash-3",
    image: "your-image-3",
    politicianId: "3",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    cloudinaryDir: "your-cloudinary-dir-4",
    contactId: "4",
    customDomain: "custom-domain-4",
    description: "Website description 4",
    myHistory: "Website history 4",
    name: "Website 4",
    politicianPhoto: "",
    theme: "blue",
    subdomain: "subdomain-4",
    message404: "Parabéns! Você encontrou uma página que não existe.",
    logo: "your-logo-4",
    font: "font-cal",
    imageBlurhash: "your-image-blurhash-4",
    image: "your-image-4",
    politicianId: "4",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default websites;
